defmodule VaccinationApi.Core.Vaccination do
  @moduledoc """
    Vaccination Entity
    ---
    Vaccination register
  """

  alias VaccinationApi.Core.{HealthProfessional, Person, Vaccine}
  use VaccinationApi.Schema

  @shot_enum [:shot_1, :shot_2, :shot_3, :shot_4]

  generate_bee do
    schema "vaccination" do
      field :shot, Ecto.Enum, values: @shot_enum, bee: [required: true]
      field :date, :utc_datetime, bee: [required: true]
      # should be autogenerated. In future, make a feature to validate it
      field :token, :string

      timestamps()

      belongs_to :person, Person
      belongs_to :health_professional, HealthProfessional
      belongs_to :vaccine, Vaccine
    end
  end

  def changeset(model, attrs), do: changeset_(model, attrs, :insert)
  def changeset_insert(model, attrs), do: changeset_(model, attrs, :insert)
  def changeset_update(model, attrs), do: changeset_(model, attrs, :update)

  defmodule Api do
    @moduledoc false

    @schema VaccinationApi.Core.Vaccination
    use Bee.Api
  end
end
